FROM ubuntu:16.04

RUN set -x \
    && apt-get update \
    && apt-get install gnupg openjdk-8-jre-headless curl gdal-bin tesseract-ocr \
        tesseract-ocr-eng tesseract-ocr-jpn -y \
    && curl -sL https://deb.nodesource.com/setup_10.x | bash - \
    && apt-get install -y nodejs build-essential git vim \  
    && mkdir /webapp

WORKDIR /webapp

CMD ["node"]